project:
  type: website
  render:
    - "*.qmd"
    - "!assets/"
    - "!apps/"
    - "!assignments/"
  resources:
    - "assets/"
    - "apps/bin/"
    - "assignments/"

website:
  title: "Teaching with Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home

    right:
      - text: Slides
        menu:
          - text: "Posit::conf(2025) talk"
            href: slides/talk.qmd
        
      - text: Worksheets
        menu:
          - text: "Example worksheet"
            href: worksheets/worksheet.qmd
          
      - text: Resources
        menu:
          - text: "Example shiny app"
            href: apps/bin/shiny-example
          - text: "Example assignment template"
            href: assignments/assignment.qmd
        
    tools:
      - icon: github
        href: "https://github.com/clauswilke/PositConf2025"

format:
  html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
  live-html:
    theme:
      light: cosmo
      dark: [solar, theme-dark.scss]
    css: styles.css
    toc: true
execute: 
  freeze: auto


