---
title: "Teaching data visualization with R<br>entirely in Quarto"
author: "Claus O. Wilke"
date: last-modified
format: 
  revealjs:
    theme:
      - default
      - Wilke-theme.scss
    auto-stretch: false
execute:
  fig-format: svg
  fig-asp: 0.618
  fig-width: 5.5
---

## Hook

Learnr sessions break on edupod

::: {.notes}
Possible images:

https://unsplash.com/photos/a-woman-sitting-in-front-of-a-laptop-computer-f2JMVDnarks
https://unsplash.com/photos/a-person-sitting-at-a-desk-with-a-laptop-and-a-cell-phone-QFe8yjZcirg
https://unsplash.com/photos/a-woman-sitting-in-front-of-a-laptop-computer-dJpBpPUevSA
https://unsplash.com/photos/a-woman-covering-her-face-while-looking-at-a-laptop-yusHnkBhF3Q
:::


## Requirements for an R-based data science class

:::{.small-font}
- Website
- Slides with code and output
- Interactive exercises
- Student assignments
- Demo/support apps
:::

## Challenges: Interactive exercises

:::{.small-font}
- shiny/learnr requires a backend webserver
- alternatively, students can run learnr documents locally, but that's ugly
:::

## Challenges: Student assignments

:::{.small-font}
- in general, pdf is the best format for submissions
- converting markdown into pdf is complicated (latex installation etc.)
:::

## Challenges: Demo/support apps

:::{.small-font}
- Same problems as learnr documents, need webserver or run locally
:::

## Quarto with webr and typst can do everything we need


## I first saw all the puzzle pieces coming together at Posit::Conf(2024)


## What is the benefit

- A single framework
- live exercises are so much easier
- students have carry-over

